### ISSUE TITLE
Dynamic Patch Hook on BigSur

### ISSUE THREAD

**Issue by max-frai** [steven-michaud/HookCase#18]
Hello, I build HookCase, loaded kernel module. So I try `dynamic-hooking` example:

`HC_INSERT_LIBRARY=......./HookCase/Examples/dynamic-hooking/hook.dylib /Applications/Safari.app/Contents/MacOS/Safari`

And there is no log from hooks. So it looks like dynamic hook works with main function and should be called for any application, yes? What could be wrong here?

**Comment by steven-michaud** [comment]
HookCase doesn't yet work on BigSur.

I typically don't add support for a new version of macOS until it's been released.

You shouldn't have been able to load HookCase at all on BigSur. `kextutil /usr/local/sbin/HookCase.kext` should have failed, and `kextstat` should not have listed `org.smichaud.HookCase`.

**Comment by max-frai** [comment]
Yes, you are right. `kextstat` is missing for `HookCase`. Okay, thank you. Will wait for support of BigSur.
