### ISSUE TITLE
HookCase doesn't (yet) support macOS 12

### ISSUE THREAD

**Issue by myrontan** [steven-michaud/HookCase#30]
Hi, Steven

Error Domain=KMErrorDomain Code=30 "Validating extension failed: Kext org.smichaud.HookCase v5.0.5 in executable kext bundle org.smichaud.HookCase at HookCase/HookCase/build/Release/HookCase.kext:

Could you try HookCase on macOS 12? Thanks

**Comment by steven-michaud** [comment]
HookCase doesn't yet support macOS 12.

I'm working on adding support. But Apple has made some changes that are difficult to work around -- particularly those to `dyld`. I expect it'll be another week or two before I'm done.

**Comment by steven-michaud** [comment]
I just released HookCase version 6.0. Please try it out.

This bug should now be fixed.

**Comment by myrontan** [comment]
Great!
