### ISSUE TITLE
Error in "sudo kmutil load -p /usr/local/sbin/HookCase.kext"  macOS Big Sur 11.6.1

### ISSUE THREAD

**Issue by nightlight89** [steven-michaud/HookCase#32]
![截屏2022-01-13 上午9 46 57](https://user-images.githubusercontent.com/16662984/149254934-bdf42e8c-121f-418e-9ae3-525e10397a00.png)

**Comment by steven-michaud** [comment]
You see these errors because your `/usr/local/sbin` directory has the wrong permissions, which were inherited by `HookCase.kext` when you copied it there.

To fix the problem:

`sudo chown root:wheel /usr/local/sbin`
`sudo chown -R root:wheel /usr/local/sbin/HookCase.kext`

**Comment by steven-michaud** [comment]
> You see these errors because your /usr/local/sbin directory has the wrong permissions

Oops, I should have said "wrong ownership".

**Comment by nightlight89** [comment]
it's ok now thanks
