### ISSUE TITLE
not Found private symbol "_proc_lock" and "_proc_unlock"  On Intel hardware for MacOS 12.5

### ISSUE THREAD

**Issue by ccp10841054** [steven-michaud/HookCase#37]
kernel_dlsym("_proc_lock")

kernel_dlsym("_proc_unlock")

return NULL;

**Comment by steven-michaud** [comment]
The macOS 12.5 kernel doesn't contain global symbols with either of these names. So kernel_dlsym() will, of course, return NULL on both of them.

You can only use kernel_dlsym() on symbols that are named in the kernel's symbol table. To get a list of these symbols, do `nm -pam /System/Library/Kernels/kernel`.

But you shouldn't be altering the HookCase.kext kernel extension's code. You should be writing hook libraries, emulating the example library in https://github.com/steven-michaud/HookCase/tree/master/HookLibraryTemplate. There you can use module_dlsym().

**Comment by ccp10841054** [comment]
But I can found private symbol "_kauth_listen_scope"、“_sflt_register”、“_sock_getsockname”On Intel hardware for MacOS 12.5. these symbols also not get ,do nm -pam /System/Library/Kernels/kernel.why?
